# Generated by Django 4.2.2 on 2023-07-01 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersContact',
            new_name='mapping_User_Contact',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='UserNumber',
            new_name='UserPhoneNumber',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='UserNumer',
            new_name='UserPhoneNumer',
        ),
    ]
