# Generated by Django 4.2.2 on 2023-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userscontact_mapping_user_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='UserEmail',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
